# Project Euler problem #2
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# See https://projecteuler.net/problem=2

  n <- 4E6 #upper treshold
  i <- 1 #incrementor
  f <- 1 #first increment
  
  fibonacci <- c(0,1,1) #first two instances of Fibonacci-sequence
  
  #creating a fibonacci-sequence from
  while(f < n){
    f <- f+fibonacci[i]
    fibonacci[2+i] <- f
    i <- i+1
  }
  
  fibonacci <- fibonacci[which(fibonacci<=4E6)]

  even <- fibonacci[which(fibonacci %% 2 == 0)] # all even
  uneven <- fibonacci[which(fibonacci %% 2 != 0)] # all uneven (not that it matters...)
  
  solution <- sum (even)
  
  cat("the solution is: ", solution)
  
